schematizerdatabase:
    build: schema/

schematizerconfigs:
    build: acceptance/configs/

schematizerservice:
    build: .
    dockerfile: Dockerfile
    links:
        - schematizerdatabase
    volumes_from:
        - schematizerconfigs
    ports:
        - "49257:8888"
